/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo_practica2;

import javax.swing.JOptionPane;

/**
 *
 * @author PcNitro
 */
public class VentanaViaje extends javax.swing.JFrame {

    /**
     * Creates new form VentanaViaje
    */
    Listas lista_general = ejemplo_practica2.Ejemplo_Practica2.listas;
    
    public VentanaViaje() {
        initComponents();
        
        cbRutaInicial.removeAllItems();
        for (String inicio: lista_general.obtenerPuntoInicial()) {
            cbRutaInicial.addItem(inicio);
        }
        
        cbRutaFinal.removeAllItems();
        for (String fin: lista_general.obtenerPuntoFinal()) {
            cbRutaFinal.addItem(fin);
        }
        
        cbTransporte.removeAllItems();
        for (String transporte: lista_general.obtenerTransportes()) {
            cbTransporte.addItem(transporte);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbRutaInicial = new javax.swing.JComboBox<>();
        cbRutaFinal = new javax.swing.JComboBox<>();
        cbTransporte = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbRutaInicial, 0, 215, Short.MAX_VALUE)
                            .addComponent(cbRutaFinal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(cbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRutaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(cbRutaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String inicio = (String) cbRutaInicial.getSelectedItem();
        String fin = (String) cbRutaFinal.getSelectedItem();
        //JOptionPane.showMessageDialog(null, "La distancia que hay es de: " + lista_general.obtenerDistancia(inicio, fin));
        
        String nombreTransporte = (String) cbTransporte.getSelectedItem();
        Transporte transporte = lista_general.obtenerObjetoTransporte(nombreTransporte);
        //JOptionPane.showMessageDialog(null, transporte.getNombre());
        
        //Iniciar Viaje
        //(String inicio, String fin, double distancia, Transporte transporte)
        double distanciaPuntos = lista_general.obtenerDistancia(inicio, fin);
        //lista_general.guardarViajes(new Viaje(inicio, fin, distanciaPuntos, transporte));
        Viaje viaje1 = new Viaje(inicio, fin, distanciaPuntos, transporte);
        System.out.println("*************** Primer viaje ***********************");
        
        for (Piloto piloto: lista_general.lista_pilotos) {
            System.out.println(piloto.getNombre());
            if (piloto.estaDisponible()) {
                viaje1.asignarPilotoViaje(piloto);
                viaje1.getTransporte().asignarPilotoTransporte(piloto);
                break;
            }
        }
        
        if (viaje1.getPiloto() == null) {
            System.out.println("No hay pilotos por el momento");
        }
        
        Transporte transporte1 = viaje1.getTransporte();
        transporte1.iniciarViaje(200);
        Thread hilo = new Thread(transporte1);

        hilo.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbRutaFinal;
    private javax.swing.JComboBox<String> cbRutaInicial;
    private javax.swing.JComboBox<String> cbTransporte;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
